LAB_NAME=TCP ISN Covert Channel Lab
LAB_AUTHOR=Marco Scarpa
LAB_DESCRIPTION=Covert Channel on TCP Initial Sequence Number with Reverse Shell and Network-Based Detection

attacker[0]=net_ext
router[0]=net_ext
router[1]=net_int
victim[0]=net_int
monitor[0]=net_ext
monitor[1]=net_int
monitor[image]=marcoscarpa04/snort3-kathara
